version: '3.7'

services:
  croni:
    image: atareao/croni:v1.1
    init: true
    restart: unless-stopped
    depends_on:
      - pyblisher
    networks:
      - internal
    volumes:
      - ./crontab:/crontab

  pyblisher:
    build: .
    image: atareao/pyblisher:v1.3
    init: true
    env_file:
      - ./.env
    volumes:
      - ./database.db:/app/database.db
      - ./peertube.toml:/app/peertube.toml
    networks:
      - internal

networks:
  internal: {}
