version: '3'

services:
  croni:
    image: atareao/croni:v1.1
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./crontab:/crontab

  pyblisher:
    build: .
    image: atareao/pyblisher:v1.0
    env_file:
      - ./.env
    volumes:
      - ./database.db:/app/database.db
      - ./peertube.toml:/app/peertube.toml
    networks:
      - internal

networks:
  internal: {}
