services:
  croni:
    image: atareao/croni:v1.1
    init: true
    restart: unless-stopped
    depends_on:
      - pyblisher
    networks:
      - internal
    volumes:
      - ./crontab:/crontab

  pyblisher:
    build: .
    image: atareao/pyblisher:v1.7.0
    init: true
    env_file:
      - ./.env
    volumes:
      - ./database.db:/app/database.db
      - ./peertube.toml:/app/peertube.toml
      - ./cookies.txt:/app/cookies.txt
    networks:
      - internal
    ports:
      - 8000:8000


networks:
  internal: {}
